### PR TITLE
Added code for CountingSort using java

### PR DESCRIPTION
**Pull request by sunilseervi6**
Added code for countingsort algorithm .Kindly accept my PR and Merge.

### CODE REVIEW

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello @sunilseervi6  Please Read the Contributing guidelines before creating PR

**Comment by ismaelsadeeq** [comment]
@fz3hra Are you willing to work on this?

**Comment by fz3hra** [comment]
@ismaelsadeeq alright, assign it to me

**Comment by ismaelsadeeq** [comment]
Thanks closing this

**Pull request closed without merging**
