### PR TITLE
Adding MergeSort in Java

### PR DESCRIPTION
**Pull request by TangoBeee**

### CODE REVIEW

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello @TangoBeee  Kindly remove the first Quick sort  Algorithm explation 
Thanks

**Comment by TangoBeee** [comment]
Why tho?

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
HI @TangoBeee  in Sorting/MergeSortJava/ReadMe.md
Please remove 
`# Quick Sort in java`
`                                `
`Time complexity - O(n log(n))`
`Space Complexity - O(log(n))`
`                                                 `
`[Algorithm Explanation](https://www.baeldung.com/java-quicksort)`

**Comment by TangoBeee** [comment]
DONE

**Review by ismaelsadeeq — APPROVED** [review]
Great.

**Pull request merged**
