### PR TITLE
🎉 added moore's voting algorithm

### PR DESCRIPTION
**Pull request by baimamboukar**

### CODE REVIEW

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hi Man Moore voting algorithm is an algorithm itself you should create a new folder for it.

**Comment by baimamboukar** [comment]
> Hi Man Moore voting algorithm is an algorithm itself you should create a new folder for it.

Ooohr! 😅
I taught classifying understand arrays was Ok ☄️

It is alright.... I'll do it ASAP!
By the way... Can you add more tasks/issues ? 😅

**Comment by baimamboukar** [comment]
@ismaelsadeeq I think your requested changes have been applied!
Thanks for reviewing....

**Comment by ismaelsadeeq** [comment]
Hello @baimamboukar sorry for very late response hand can you reopen this?
I am ready to review this

**Pull request closed without merging**
