### PR TITLE
Added Selection sort algorithm in Java 

### PR DESCRIPTION
**Pull request by Ashpreetwadhwa**

### CODE REVIEW

**Comment by Ashpreetwadhwa** [comment]
Can I add more algorithms.. please @ismaelsadeeq

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello @Ashpreetwadhwa 
You have not added the space complexity of your solution in the Readme file and also the explanation of the algorithm should be in a blog post.

**Comment by Ashpreetwadhwa** [comment]
Just view it now does it is ok

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
@Ashpreetwadhwa  Thanks for conttributing
`In your ReadMe.md line 3`
Please change 
`You can suggest go and read about it from the above blog post`

to 
`Read about Selection Sort in the blog post above`

**Comment by Ashpreetwadhwa** [comment]
Ok

**Comment by Ashpreetwadhwa** [comment]
please check it know

**Comment by Ashpreetwadhwa** [comment]
Please add hacktoberfest accepted label

**Pull request merged**
