### PR TITLE
[Feature]: Added the linked list (Singly, Doubly, and Circularly) using C language

### PR DESCRIPTION
**Pull request by Ddilibe**

### CODE REVIEW

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello @Ddilibe Thank you for your contributions there are few changes that you need to add to the readme file for yout PR to be merged.
1 . On your instructions you wrote
 Create your main function to test this. 
Replace it with the section `<main_file>`in the command. 
You've not added how to create the main function.
2. You should reference a blog post, video explaining the Data Structure you have implemented, or write a post explaining your thought on it
3. Inside LinkedList folder create another Folder C. and insert you solutions inside.

**Comment by Ddilibe** [comment]
Hi @ismaelsadeeq, I will start working on it Immediately. Thanks for the feed back.

**Comment by Ddilibe** [comment]
Hi @ismaelsadeeq , I am done working on it. Please, take a look at it.

**Comment by ismaelsadeeq** [comment]
Okay I will Review soon

**Comment by ismaelsadeeq** [comment]
Hello  Man @Ddilibe  their is a .gitignore file in the Linkedlist, have you used any library/packages for the implementation?

**Comment by Ddilibe** [comment]
@ismaelsadeeq, I had to remove some files that appeared during the complications

**Pull request merged**
