### PR TITLE
Added MergeSort and BubbleSort using Javascript

### PR DESCRIPTION
**Pull request by farhanpro**
Hello please check and if you liked it then merge it

### CODE REVIEW

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello You have not add a Readme to the explanation of Bubble sort and MergeSort.
And they all should be in a separate directory

**Comment by farhanpro** [comment]
Sorry about that I will fix it asap and commit it sorry for the inconvenience

**Comment by farhanpro** [comment]
Done please check and provide feedBack

**Review by ismaelsadeeq — CHANGES_REQUESTED** [review]
Hello @farhanpro Nice work Man.
The Notes folder is not needed here your explanation was okay and the link.
Reove them and your PR will be merged

**Comment by farhanpro** [comment]
okay i will remove the notes folder

**Pull request merged**
